branch-defaults:
  main:
    environment: ShibaApp-dev
    group_suffix: null
environment-defaults:
  ShibaApp-dev:
    branch: null
    repository: null
global:
  application_name: ShibaApp
  branch: null
  default_ec2_keyname: latest-kaal
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
